
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: demo-flask-server
  namespace: test-demo
spec:
  selector:
    matchLabels:
      app: sts-flask # has to match .spec.template.metadata.labels
  
  replicas: 3 # by default is 1
  template:
    metadata:
      labels:
        app: sts-flask # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: container-0
        image: ramyachigatapu/python-flask:demo
        ports:
        - containerPort: 5000
          name: web
---
apiVersion: v1
kind: Service
metadata:
  name: python-flask-service
  namespace: test-demo
spec:
  type: NodePort
  selector:
    app: test-flask
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 5000
      targetPort: 5000
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30007
---

