apiVersion: v1
kind: Pod
metadata:
  name: pod-with-pvc
  labels:
    name: pod-with-pvc
spec:
  containers:
  - name: pod-with-pvc
    image: ramyachigatapu/python-flask:demo
    ports:
      - containerPort: 8080
        name: www
    volumeMounts:
      - name: www-persistent-storage
        mountPath: /home/mount_vol/storage
  volumes:
    - name: www-persistent-storage
      persistentVolumeClaim:
        claimName: ramyas-pvc
