apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ramyas-pvc
spec:
  volumeName: ramyas-pv
  storageClassName: local-storage
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
